-- Tabla para el estado del sistema
CREATE TABLE sistema (
    id INT PRIMARY KEY DEFAULT 1,
    encendido BOOLEAN DEFAULT FALSE,
    turno_actual TEXT DEFAULT 'turno1'
);

-- Insertar estado inicial
INSERT INTO sistema (id, encendido, turno_actual) VALUES (1, FALSE, 'turno1');

-- Tabla para lecturas individuales
CREATE TABLE lecturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    color TEXT NOT NULL,
    turno TEXT NOT NULL
);

-- Tabla para contadores por turno
CREATE TABLE turnos (
    turno TEXT PRIMARY KEY,
    rojo INT DEFAULT 0,
    verde INT DEFAULT 0,
    azul INT DEFAULT 0
);

-- Insertar turnos iniciales
INSERT INTO turnos (turno, rojo, verde, azul) VALUES 
('turno1', 0, 0, 0),
('turno2', 0, 0, 0),
('turno3', 0, 0, 0);

-- Función RPC para incrementar contador atómicamente
CREATE OR REPLACE FUNCTION incrementar_contador(p_turno TEXT, p_color TEXT)
RETURNS VOID AS $$
BEGIN
    IF p_color = 'ROJO' THEN
        UPDATE turnos SET rojo = rojo + 1 WHERE turno = p_turno;
    ELSIF p_color = 'VERDE' THEN
        UPDATE turnos SET verde = verde + 1 WHERE turno = p_turno;
    ELSIF p_color = 'AZUL' THEN
        UPDATE turnos SET azul = azul + 1 WHERE turno = p_turno;
    END IF;
END;
$$ LANGUAGE plpgsql;
