-- Tabla para registrar las sesiones de trabajo (Turnos)
CREATE TABLE sesiones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inicio TIMESTAMPTZ DEFAULT NOW(),
    fin TIMESTAMPTZ,
    turno TEXT NOT NULL,
    total_rojo INT DEFAULT 0,
    total_verde INT DEFAULT 0,
    total_azul INT DEFAULT 0
);

-- Política de seguridad (opcional, permite todo por ahora)
ALTER TABLE sesiones ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir todo en sesiones" ON sesiones FOR ALL USING (true) WITH CHECK (true);
